<div id="view-content">
	<h2>Lista de contactos</h2>
</div>

<div class="row">
	<div class="col-md-5">
		<div id="lista" class="list-group">
			<a href="#" class="list-group-item active btn-nuevo" >
				Agregar nuevo ...
			</a>
			<?php foreach ($this->contactos as $contacto):?>
			<a href="#" class="list-group-item contacto" 
			data-id="<?=$contacto['IdContacto']?>">
				<?= $contacto['Nombre'] ?>
			</a>
			<?php endforeach; ?>
		</div> <!-- fin de lista -->
	</div>
	<div class="col-md-7" >
		<div class="panel panel-default">
			<div class="panel-heading">Detalles de contacto </div>
			<div class="panel-body" id="detalles">
				
			</div>
		</div>
		
	</div>
</div>

<div id="nuevo">
	<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</div><!-- fin de nuevo -->

<div id="ver">
	
</div><!-- fin de ver -->
 <?php print $this->headScript()->appendFile($this->baseUrl().'/bower_components/mustache.js/mustache.min.js') ?>
<script>

let view="<h1>{{Nombre}}</h1> <p>Correo electrónico: <a href='mailto:{{Email}}'>{{Email}}</a> </p> <p>Dirección: {{Direccion}}</p> <a href='#' class='btn btn-success pull-right'> Editar</a> ";

	$('.contacto').on('click',function(){
		let id=$(this).data('id');
		$.ajax({
			url:"<?= $this->baseUrl()."/app/ver/" ?>",
			data:{id:id},
			type:'post',
			dataType:'json',
			success:function(resp){
				$('#detalles').html(Mustache.render(view,resp));
			}
		});
	});

	$('.btn-nuevo').on('click',function(){
		let id=$(this).data('id');
		$.ajax({
			url:"<?= $this->baseUrl()."/app/add/" ?>",
			type:'post',
			// dataType:'json',
			success:function(resp){
				$('#detalles').html(resp);
			}
		});
	});
	$('.contacto').on('beforeSend',function(){
		let id=$(this).data('id');
		$.ajax({
			url:"<?= $this->baseUrl()."/app/add/" ?>",
			type:'post',
			// dataType:'json',
			success:function(resp){
				$('#detalles').html(resp);
			}
		});
		return false;
	});
</script>